"""SLA Bill Checker V2.0 PDF footer patch.
Adds generation date/time in IST to every generated PDF without changing SLA calculations.
"""
from datetime import datetime
from zoneinfo import ZoneInfo

try:
    import sla_logic
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Preformatted
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.enums import TA_CENTER

    def create_pdf_note_with_timestamp(output_path, title, text_body):
        generated_at = datetime.now(ZoneInfo("Asia/Kolkata")).strftime("%d-%m-%Y %I:%M %p IST")

        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=24,
            leftMargin=24,
            topMargin=24,
            bottomMargin=24,
        )
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "BSNLTitleV2", parent=styles["Heading1"], alignment=TA_CENTER,
            fontSize=15, leading=19, textColor=colors.HexColor("#0b2d6b"), spaceAfter=8,
        )
        normal_style = ParagraphStyle(
            "BSNLMonoNormalV2", parent=styles["Code"], fontName="Courier",
            fontSize=8.4, leading=11.2, leftIndent=0, rightIndent=0, textColor=colors.black,
        )
        red_style = ParagraphStyle(
            "BSNLMonoRedV2", parent=normal_style, fontName="Courier-Bold", textColor=colors.red,
        )
        blue_style = ParagraphStyle(
            "BSNLMonoBlueV2", parent=normal_style, fontName="Courier-Bold",
            textColor=colors.HexColor("#0000CC"),
        )
        footer_style = ParagraphStyle(
            "BSNLFooterV2", parent=styles["BodyText"], alignment=TA_CENTER,
            fontSize=8, leading=10, textColor=colors.grey,
        )

        red_phrases = (
            "Total Penalty (MTTR + Availability)",
            "Total Retention Pending Scrutiny",
            "Total Net Penalty Recoverable",
            "Total Manual Penalties/Recoveries",
        )
        blue_phrases = (
            "MTTR Retention Pending Scrutiny",
            "Availability Retention Pending Scrutiny",
            "Retention:",
            "Retention for 1% Re-laying",
        )

        story = [
            Paragraph(title, title_style),
            HRFlowable(width="100%", thickness=0.8, color=colors.HexColor("#0b2d6b")),
            Spacer(1, 10),
        ]
        for raw_line in str(text_body).splitlines():
            if raw_line.strip() == "":
                story.append(Spacer(1, 5))
                continue
            if any(p in raw_line for p in red_phrases):
                style = red_style
            elif any(p in raw_line for p in blue_phrases):
                style = blue_style
            else:
                style = normal_style
            story.append(Preformatted(raw_line, style, maxLineLength=108))

        story.extend([
            Spacer(1, 14),
            HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey),
            Spacer(1, 6),
            Paragraph(
                f"Generated by BSNL SLA Bill Checker | V2.0 | {generated_at}",
                footer_style,
            ),
        ])
        doc.build(story)

    sla_logic.create_pdf_note = create_pdf_note_with_timestamp
except Exception:
    # Never block the application if the optional footer patch cannot load.
    pass
